// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: directory.proto
#ifndef GRPC_directory_2eproto__INCLUDED
#define GRPC_directory_2eproto__INCLUDED

#include "directory.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace directory {

class DirectoryService final {
 public:
  static constexpr char const* service_full_name() {
    return "directory.DirectoryService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status hello(::grpc::ClientContext* context, const ::directory::Empty& request, ::directory::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::directory::Empty>> Asynchello(::grpc::ClientContext* context, const ::directory::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::directory::Empty>>(AsynchelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::directory::Empty>> PrepareAsynchello(::grpc::ClientContext* context, const ::directory::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::directory::Empty>>(PrepareAsynchelloRaw(context, request, cq));
    }
    virtual ::grpc::Status register_segment(::grpc::ClientContext* context, const ::directory::RegisterRequest& request, ::directory::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::directory::Empty>> Asyncregister_segment(::grpc::ClientContext* context, const ::directory::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::directory::Empty>>(Asyncregister_segmentRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::directory::Empty>> PrepareAsyncregister_segment(::grpc::ClientContext* context, const ::directory::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::directory::Empty>>(PrepareAsyncregister_segmentRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void hello(::grpc::ClientContext* context, const ::directory::Empty* request, ::directory::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void hello(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::directory::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void register_segment(::grpc::ClientContext* context, const ::directory::RegisterRequest* request, ::directory::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void register_segment(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::directory::Empty* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::directory::Empty>* AsynchelloRaw(::grpc::ClientContext* context, const ::directory::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::directory::Empty>* PrepareAsynchelloRaw(::grpc::ClientContext* context, const ::directory::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::directory::Empty>* Asyncregister_segmentRaw(::grpc::ClientContext* context, const ::directory::RegisterRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::directory::Empty>* PrepareAsyncregister_segmentRaw(::grpc::ClientContext* context, const ::directory::RegisterRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status hello(::grpc::ClientContext* context, const ::directory::Empty& request, ::directory::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::directory::Empty>> Asynchello(::grpc::ClientContext* context, const ::directory::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::directory::Empty>>(AsynchelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::directory::Empty>> PrepareAsynchello(::grpc::ClientContext* context, const ::directory::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::directory::Empty>>(PrepareAsynchelloRaw(context, request, cq));
    }
    ::grpc::Status register_segment(::grpc::ClientContext* context, const ::directory::RegisterRequest& request, ::directory::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::directory::Empty>> Asyncregister_segment(::grpc::ClientContext* context, const ::directory::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::directory::Empty>>(Asyncregister_segmentRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::directory::Empty>> PrepareAsyncregister_segment(::grpc::ClientContext* context, const ::directory::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::directory::Empty>>(PrepareAsyncregister_segmentRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void hello(::grpc::ClientContext* context, const ::directory::Empty* request, ::directory::Empty* response, std::function<void(::grpc::Status)>) override;
      void hello(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::directory::Empty* response, std::function<void(::grpc::Status)>) override;
      void register_segment(::grpc::ClientContext* context, const ::directory::RegisterRequest* request, ::directory::Empty* response, std::function<void(::grpc::Status)>) override;
      void register_segment(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::directory::Empty* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::directory::Empty>* AsynchelloRaw(::grpc::ClientContext* context, const ::directory::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::directory::Empty>* PrepareAsynchelloRaw(::grpc::ClientContext* context, const ::directory::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::directory::Empty>* Asyncregister_segmentRaw(::grpc::ClientContext* context, const ::directory::RegisterRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::directory::Empty>* PrepareAsyncregister_segmentRaw(::grpc::ClientContext* context, const ::directory::RegisterRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_hello_;
    const ::grpc::internal::RpcMethod rpcmethod_register_segment_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status hello(::grpc::ServerContext* context, const ::directory::Empty* request, ::directory::Empty* response);
    virtual ::grpc::Status register_segment(::grpc::ServerContext* context, const ::directory::RegisterRequest* request, ::directory::Empty* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_hello() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status hello(::grpc::ServerContext* context, const ::directory::Empty* request, ::directory::Empty* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requesthello(::grpc::ServerContext* context, ::directory::Empty* request, ::grpc::ServerAsyncResponseWriter< ::directory::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_register_segment : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_register_segment() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_register_segment() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status register_segment(::grpc::ServerContext* context, const ::directory::RegisterRequest* request, ::directory::Empty* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestregister_segment(::grpc::ServerContext* context, ::directory::RegisterRequest* request, ::grpc::ServerAsyncResponseWriter< ::directory::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_hello<WithAsyncMethod_register_segment<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_hello() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::directory::Empty, ::directory::Empty>(
          [this](::grpc::ServerContext* context,
                 const ::directory::Empty* request,
                 ::directory::Empty* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->hello(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status hello(::grpc::ServerContext* context, const ::directory::Empty* request, ::directory::Empty* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void hello(::grpc::ServerContext* context, const ::directory::Empty* request, ::directory::Empty* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_register_segment : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_register_segment() {
      ::grpc::Service::experimental().MarkMethodCallback(1,
        new ::grpc::internal::CallbackUnaryHandler< ::directory::RegisterRequest, ::directory::Empty>(
          [this](::grpc::ServerContext* context,
                 const ::directory::RegisterRequest* request,
                 ::directory::Empty* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->register_segment(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_register_segment() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status register_segment(::grpc::ServerContext* context, const ::directory::RegisterRequest* request, ::directory::Empty* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void register_segment(::grpc::ServerContext* context, const ::directory::RegisterRequest* request, ::directory::Empty* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_hello<ExperimentalWithCallbackMethod_register_segment<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_hello() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status hello(::grpc::ServerContext* context, const ::directory::Empty* request, ::directory::Empty* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_register_segment : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_register_segment() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_register_segment() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status register_segment(::grpc::ServerContext* context, const ::directory::RegisterRequest* request, ::directory::Empty* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_hello() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status hello(::grpc::ServerContext* context, const ::directory::Empty* request, ::directory::Empty* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requesthello(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_register_segment : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_register_segment() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_register_segment() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status register_segment(::grpc::ServerContext* context, const ::directory::RegisterRequest* request, ::directory::Empty* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestregister_segment(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_hello() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->hello(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status hello(::grpc::ServerContext* context, const ::directory::Empty* request, ::directory::Empty* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void hello(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_register_segment : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_register_segment() {
      ::grpc::Service::experimental().MarkMethodRawCallback(1,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->register_segment(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_register_segment() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status register_segment(::grpc::ServerContext* context, const ::directory::RegisterRequest* request, ::directory::Empty* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void register_segment(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_hello() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::directory::Empty, ::directory::Empty>(std::bind(&WithStreamedUnaryMethod_hello<BaseClass>::Streamedhello, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status hello(::grpc::ServerContext* context, const ::directory::Empty* request, ::directory::Empty* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedhello(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::directory::Empty,::directory::Empty>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_register_segment : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_register_segment() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::directory::RegisterRequest, ::directory::Empty>(std::bind(&WithStreamedUnaryMethod_register_segment<BaseClass>::Streamedregister_segment, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_register_segment() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status register_segment(::grpc::ServerContext* context, const ::directory::RegisterRequest* request, ::directory::Empty* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedregister_segment(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::directory::RegisterRequest,::directory::Empty>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_hello<WithStreamedUnaryMethod_register_segment<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_hello<WithStreamedUnaryMethod_register_segment<Service > > StreamedService;
};

}  // namespace directory


#endif  // GRPC_directory_2eproto__INCLUDED
